# Generated by Django 5.0 on 2024-01-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_alter_vagas_tipo_de_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='tipo_de_vaga',
            field=models.CharField(choices=[('CLT', 'clt'), ('PJ', 'pj'), ('MENOR APRENDIZ', 'menor aprendiz'), ('ESTAGIO', 'estagio'), ('FREELANCER', 'freelancer'), ('DIARISTAS', 'diaristas')], default='', max_length=100),
        ),
    ]
