# Generated by Django 5.0 on 2024-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_vagas_numero_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='tipo_de_vaga',
            field=models.CharField(choices=[('PJ', 'pj'), ('FREELANCER', 'freelancer'), ('DIARISTAS', 'diaristas')], default='', max_length=100),
        ),
    ]
