# Generated by Django 5.0 on 2024-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroForms',
        ),
        migrations.DeleteModel(
            name='LoginForms',
        ),
    ]
