# Generated by Django 5.0 on 2024-01-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_empresa',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
