# Generated by Django 5.0 on 2024-01-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_usuario_email_empresa_usuario_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
