# Generated by Django 5.0 on 2024-01-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_curriculo_curriculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('titulo_profissional', models.CharField(max_length=150)),
                ('descricao_pessoal', models.TextField()),
                ('resumo_experiencia_profissional', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curriculo',
        ),
    ]
