# Generated by Django 5.0 on 2024-01-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_resumo_usuario_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='pago',
            field=models.BooleanField(default=True),
        ),
    ]
