# Generated by Django 5.0 on 2024-01-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_resumo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumo',
            name='pago',
        ),
    ]
