# Generated by Django 5.0 on 2024-02-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_resumo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='telefone',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
